// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastMean
double fastMean(const arma::vec& X);
RcppExport SEXP _manytestsr_fastMean(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastMean(X));
    return rcpp_result_gen;
END_RCPP
}
// fastMedian
double fastMedian(const arma::vec& X);
RcppExport SEXP _manytestsr_fastMedian(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastMedian(X));
    return rcpp_result_gen;
END_RCPP
}
// fastVar
double fastVar(const arma::vec& X);
RcppExport SEXP _manytestsr_fastVar(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastVar(X));
    return rcpp_result_gen;
END_RCPP
}
// fastcolMeans
arma::vec fastcolMeans(const arma::mat& X);
RcppExport SEXP _manytestsr_fastcolMeans(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastcolMeans(X));
    return rcpp_result_gen;
END_RCPP
}
// fastrowMeans
arma::vec fastrowMeans(const arma::mat& X);
RcppExport SEXP _manytestsr_fastrowMeans(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastrowMeans(X));
    return rcpp_result_gen;
END_RCPP
}
// fastrowMads
arma::vec fastrowMads(const arma::mat& X);
RcppExport SEXP _manytestsr_fastrowMads(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastrowMads(X));
    return rcpp_result_gen;
END_RCPP
}
// fastrowMads2
arma::vec fastrowMads2(const arma::mat& X);
RcppExport SEXP _manytestsr_fastrowMads2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastrowMads2(X));
    return rcpp_result_gen;
END_RCPP
}
// fastrowMaxs
arma::vec fastrowMaxs(const arma::mat& X);
RcppExport SEXP _manytestsr_fastrowMaxs(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastrowMaxs(X));
    return rcpp_result_gen;
END_RCPP
}
// fastrowMaxs2
SEXP fastrowMaxs2(SEXP x);
RcppExport SEXP _manytestsr_fastrowMaxs2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fastrowMaxs2(x));
    return rcpp_result_gen;
END_RCPP
}
// fastcova
arma::mat fastcova(const arma::mat& X);
RcppExport SEXP _manytestsr_fastcova(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastcova(X));
    return rcpp_result_gen;
END_RCPP
}
// zscore_vec
Rcpp::NumericVector zscore_vec(const arma::vec& X);
RcppExport SEXP _manytestsr_zscore_vec(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_vec(X));
    return rcpp_result_gen;
END_RCPP
}
// vecdist_arma
arma::mat vecdist_arma(const arma::vec& x);
RcppExport SEXP _manytestsr_vecdist_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vecdist_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// vecdist3
arma::mat vecdist3(const arma::vec& A);
RcppExport SEXP _manytestsr_vecdist3(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(vecdist3(A));
    return rcpp_result_gen;
END_RCPP
}
// vecdist2
Rcpp::NumericMatrix vecdist2(const Rcpp::NumericVector& x);
RcppExport SEXP _manytestsr_vecdist2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vecdist2(x));
    return rcpp_result_gen;
END_RCPP
}
// avg_rank_arma
arma::vec avg_rank_arma(const arma::vec& x);
RcppExport SEXP _manytestsr_avg_rank_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(avg_rank_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_and_trans
Rcpp::List fast_dists_and_trans(const arma::vec& x, const arma::vec& Z);
RcppExport SEXP _manytestsr_fast_dists_and_trans(SEXP xSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans(x, Z));
    return rcpp_result_gen;
END_RCPP
}
// avg_rank
Rcpp::NumericVector avg_rank(const Rcpp::NumericVector& x);
RcppExport SEXP _manytestsr_avg_rank(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(avg_rank(x));
    return rcpp_result_gen;
END_RCPP
}
// fastmad
double fastmad(const Rcpp::NumericVector& x);
RcppExport SEXP _manytestsr_fastmad(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmad(x));
    return rcpp_result_gen;
END_RCPP
}
// fastmad_arma
double fastmad_arma(const arma::vec& x);
RcppExport SEXP _manytestsr_fastmad_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmad_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_and_trans_by_unit_arma
Rcpp::List fast_dists_and_trans_by_unit_arma(const arma::vec& x, const arma::vec& Z);
RcppExport SEXP _manytestsr_fast_dists_and_trans_by_unit_arma(SEXP xSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans_by_unit_arma(x, Z));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_by_unit_arma2_par
Rcpp::List fast_dists_by_unit_arma2_par(const arma::vec& x, const arma::vec& Z, const int threads);
RcppExport SEXP _manytestsr_fast_dists_by_unit_arma2_par(SEXP xSEXP, SEXP ZSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_by_unit_arma2_par(x, Z, threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_and_trans_by_unit_arma2
Rcpp::List fast_dists_and_trans_by_unit_arma2(const arma::vec& x, const arma::vec& Z);
RcppExport SEXP _manytestsr_fast_dists_and_trans_by_unit_arma2(SEXP xSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans_by_unit_arma2(x, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_manytestsr_fastMean", (DL_FUNC) &_manytestsr_fastMean, 1},
    {"_manytestsr_fastMedian", (DL_FUNC) &_manytestsr_fastMedian, 1},
    {"_manytestsr_fastVar", (DL_FUNC) &_manytestsr_fastVar, 1},
    {"_manytestsr_fastcolMeans", (DL_FUNC) &_manytestsr_fastcolMeans, 1},
    {"_manytestsr_fastrowMeans", (DL_FUNC) &_manytestsr_fastrowMeans, 1},
    {"_manytestsr_fastrowMads", (DL_FUNC) &_manytestsr_fastrowMads, 1},
    {"_manytestsr_fastrowMads2", (DL_FUNC) &_manytestsr_fastrowMads2, 1},
    {"_manytestsr_fastrowMaxs", (DL_FUNC) &_manytestsr_fastrowMaxs, 1},
    {"_manytestsr_fastrowMaxs2", (DL_FUNC) &_manytestsr_fastrowMaxs2, 1},
    {"_manytestsr_fastcova", (DL_FUNC) &_manytestsr_fastcova, 1},
    {"_manytestsr_zscore_vec", (DL_FUNC) &_manytestsr_zscore_vec, 1},
    {"_manytestsr_vecdist_arma", (DL_FUNC) &_manytestsr_vecdist_arma, 1},
    {"_manytestsr_vecdist3", (DL_FUNC) &_manytestsr_vecdist3, 1},
    {"_manytestsr_vecdist2", (DL_FUNC) &_manytestsr_vecdist2, 1},
    {"_manytestsr_avg_rank_arma", (DL_FUNC) &_manytestsr_avg_rank_arma, 1},
    {"_manytestsr_fast_dists_and_trans", (DL_FUNC) &_manytestsr_fast_dists_and_trans, 2},
    {"_manytestsr_avg_rank", (DL_FUNC) &_manytestsr_avg_rank, 1},
    {"_manytestsr_fastmad", (DL_FUNC) &_manytestsr_fastmad, 1},
    {"_manytestsr_fastmad_arma", (DL_FUNC) &_manytestsr_fastmad_arma, 1},
    {"_manytestsr_fast_dists_and_trans_by_unit_arma", (DL_FUNC) &_manytestsr_fast_dists_and_trans_by_unit_arma, 2},
    {"_manytestsr_fast_dists_by_unit_arma2_par", (DL_FUNC) &_manytestsr_fast_dists_by_unit_arma2_par, 3},
    {"_manytestsr_fast_dists_and_trans_by_unit_arma2", (DL_FUNC) &_manytestsr_fast_dists_and_trans_by_unit_arma2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_manytestsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
