// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_dists_and_trans_new
Rcpp::List fast_dists_and_trans_new(const arma::vec& x);
RcppExport SEXP _manytestsr_fast_dists_and_trans_new(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans_new(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_and_trans_new_omp
Rcpp::List fast_dists_and_trans_new_omp(const arma::vec& x, const int threads);
RcppExport SEXP _manytestsr_fast_dists_and_trans_new_omp(SEXP xSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans_new_omp(x, threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_and_trans_hybrid
Rcpp::List fast_dists_and_trans_hybrid(const arma::vec& x);
RcppExport SEXP _manytestsr_fast_dists_and_trans_hybrid(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans_hybrid(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_dists_and_trans_nomax_hybrid
Rcpp::List fast_dists_and_trans_nomax_hybrid(const arma::vec& x);
RcppExport SEXP _manytestsr_fast_dists_and_trans_nomax_hybrid(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dists_and_trans_nomax_hybrid(x));
    return rcpp_result_gen;
END_RCPP
}
// vecdist_arma
arma::mat vecdist_arma(const arma::vec& x);
RcppExport SEXP _manytestsr_vecdist_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vecdist_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// vecdist3_arma
arma::mat vecdist3_arma(const arma::vec& A);
RcppExport SEXP _manytestsr_vecdist3_arma(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(vecdist3_arma(A));
    return rcpp_result_gen;
END_RCPP
}
// vecdist2
Rcpp::NumericMatrix vecdist2(const Rcpp::NumericVector& x);
RcppExport SEXP _manytestsr_vecdist2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vecdist2(x));
    return rcpp_result_gen;
END_RCPP
}
// avg_rank_arma
arma::vec avg_rank_arma(const arma::vec& x);
RcppExport SEXP _manytestsr_avg_rank_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(avg_rank_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// avg_rank
Rcpp::NumericVector avg_rank(const Rcpp::NumericVector& x);
RcppExport SEXP _manytestsr_avg_rank(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(avg_rank(x));
    return rcpp_result_gen;
END_RCPP
}
// fastmad_arma
double fastmad_arma(const arma::vec& x);
RcppExport SEXP _manytestsr_fastmad_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmad_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// fastmad
double fastmad(const Rcpp::NumericVector& x, double center);
RcppExport SEXP _manytestsr_fastmad(SEXP xSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(fastmad(x, center));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_manytestsr_fast_dists_and_trans_new", (DL_FUNC) &_manytestsr_fast_dists_and_trans_new, 1},
    {"_manytestsr_fast_dists_and_trans_new_omp", (DL_FUNC) &_manytestsr_fast_dists_and_trans_new_omp, 2},
    {"_manytestsr_fast_dists_and_trans_hybrid", (DL_FUNC) &_manytestsr_fast_dists_and_trans_hybrid, 1},
    {"_manytestsr_fast_dists_and_trans_nomax_hybrid", (DL_FUNC) &_manytestsr_fast_dists_and_trans_nomax_hybrid, 1},
    {"_manytestsr_vecdist_arma", (DL_FUNC) &_manytestsr_vecdist_arma, 1},
    {"_manytestsr_vecdist3_arma", (DL_FUNC) &_manytestsr_vecdist3_arma, 1},
    {"_manytestsr_vecdist2", (DL_FUNC) &_manytestsr_vecdist2, 1},
    {"_manytestsr_avg_rank_arma", (DL_FUNC) &_manytestsr_avg_rank_arma, 1},
    {"_manytestsr_avg_rank", (DL_FUNC) &_manytestsr_avg_rank, 1},
    {"_manytestsr_fastmad_arma", (DL_FUNC) &_manytestsr_fastmad_arma, 1},
    {"_manytestsr_fastmad", (DL_FUNC) &_manytestsr_fastmad, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_manytestsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
