# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastMean <- function(X) {
    .Call(`_manytestsr_fastMean`, X)
}

fastMedian <- function(X) {
    .Call(`_manytestsr_fastMedian`, X)
}

fastVar <- function(X) {
    .Call(`_manytestsr_fastVar`, X)
}

fastcolMeans <- function(X) {
    .Call(`_manytestsr_fastcolMeans`, X)
}

fastrowMeans <- function(X) {
    .Call(`_manytestsr_fastrowMeans`, X)
}

fastrowMads <- function(X) {
    .Call(`_manytestsr_fastrowMads`, X)
}

fastrowMads4 <- function(X) {
    .Call(`_manytestsr_fastrowMads4`, X)
}

fastcolMads4 <- function(X) {
    .Call(`_manytestsr_fastcolMads4`, X)
}

fastrowMads2 <- function(X) {
    .Call(`_manytestsr_fastrowMads2`, X)
}

fastrowMads3 <- function(X) {
    .Call(`_manytestsr_fastrowMads3`, X)
}

fastrowMaxs <- function(X) {
    .Call(`_manytestsr_fastrowMaxs`, X)
}

fastrowMaxs2 <- function(x) {
    .Call(`_manytestsr_fastrowMaxs2`, x)
}

fastcova <- function(X) {
    .Call(`_manytestsr_fastcova`, X)
}

replace_na_nan <- function(x, replacement = 0) {
    .Call(`_manytestsr_replace_na_nan`, x, replacement)
}

zscore_vec2 <- function(x) {
    .Call(`_manytestsr_zscore_vec2`, x)
}

zscore_vec <- function(X) {
    .Call(`_manytestsr_zscore_vec`, X)
}

vecdist_squared <- function(A) {
    .Call(`_manytestsr_vecdist_squared`, A)
}

vecdist2 <- function(x) {
    .Call(`_manytestsr_vecdist2`, x)
}

vecdist_arma <- function(x) {
    .Call(`_manytestsr_vecdist_arma`, x)
}

avg_rank_arma <- function(x) {
    .Call(`_manytestsr_avg_rank_arma`, x)
}

fast_dists_and_trans <- function(x, Z) {
    .Call(`_manytestsr_fast_dists_and_trans`, x, Z)
}

avg_rank <- function(x) {
    .Call(`_manytestsr_avg_rank`, x)
}

fastmad_arma <- function(x) {
    .Call(`_manytestsr_fastmad_arma`, x)
}

fast_dists_and_trans_by_unit_arma <- function(x, Z) {
    .Call(`_manytestsr_fast_dists_and_trans_by_unit_arma`, x, Z)
}

fast_dists_by_unit_arma2_par <- function(x, Z, threads = 4L) {
    .Call(`_manytestsr_fast_dists_by_unit_arma2_par`, x, Z, threads)
}

fast_dists_and_trans_by_unit_arma2 <- function(x, Z) {
    .Call(`_manytestsr_fast_dists_and_trans_by_unit_arma2`, x, Z)
}

manhattan_dist <- function(x) {
    .Call(`_manytestsr_manhattan_dist`, x)
}

euc_dist_arma1 <- function(x) {
    .Call(`_manytestsr_euc_dist_arma1`, x)
}

vecdist3 <- function(x) {
    .Call(`_manytestsr_vecdist3`, x)
}

vecdist_rcpp <- function(x) {
    .Call(`_manytestsr_vecdist_rcpp`, x)
}

trimmed_mean <- function(x, trim_percent) {
    .Call(`_manytestsr_trimmed_mean`, x, trim_percent)
}

fastmad <- function(x, center) {
    .Call(`_manytestsr_fastmad`, x, center)
}

fast_huberM <- function(x, k = 1.5, tol = 1e-06, trim = .05) {
    .Call(`_manytestsr_fast_huberM`, x, k, tol, trim)
}

col_huberM <- function(dx, k = 1.5, tol = 1e-06, trim = .05) {
    .Call(`_manytestsr_col_huberM`, dx, k, tol, trim)
}

