# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastMean <- function(X) {
    .Call(`_manytestsr_fastMean`, X)
}

fastVar <- function(X) {
    .Call(`_manytestsr_fastVar`, X)
}

fastcolMeans <- function(X) {
    .Call(`_manytestsr_fastcolMeans`, X)
}

fastrowMeans <- function(X) {
    .Call(`_manytestsr_fastrowMeans`, X)
}

fastrowMads <- function(X) {
    .Call(`_manytestsr_fastrowMads`, X)
}

fastrowMads2 <- function(X) {
    .Call(`_manytestsr_fastrowMads2`, X)
}

fastrowMaxs <- function(X) {
    .Call(`_manytestsr_fastrowMaxs`, X)
}

fastrowMaxs2 <- function(x) {
    .Call(`_manytestsr_fastrowMaxs2`, x)
}

fastcova <- function(X) {
    .Call(`_manytestsr_fastcova`, X)
}

zscore_vec <- function(X) {
    .Call(`_manytestsr_zscore_vec`, X)
}

vecdist_arma <- function(x) {
    .Call(`_manytestsr_vecdist_arma`, x)
}

vecdist3 <- function(A) {
    .Call(`_manytestsr_vecdist3`, A)
}

vecdist2 <- function(x) {
    .Call(`_manytestsr_vecdist2`, x)
}

avg_rank_arma <- function(x) {
    .Call(`_manytestsr_avg_rank_arma`, x)
}

fast_dists_and_trans <- function(x, Z) {
    .Call(`_manytestsr_fast_dists_and_trans`, x, Z)
}

